### ISSUE TITLE
Species batch: could not valid the modal (iPad)

### ISSUE THREAD

**Issue by hgaden** [sumaris-net/sumaris-app#126]
polyfills.930684be0f926f1d8d85.js:1 Uncaught DOMException: Failed to execute 'setSelectionRange' on 'HTMLInputElement': The input element's type ('number') does not support selection.
    at HTMLInputElement.<anonymous> (https://test.sumaris.net/main.7b593a241c665c1baf5d.js:1:2540393)
    at t.invokeTask (https://test.sumaris.net/polyfills.930684be0f926f1d8d85.js:1:8060)
    at e.runTask (https://test.sumaris.net/polyfills.930684be0f926f1d8d85.js:1:3242)
    at e.invokeTask [as invoke] (https://test.sumaris.net/polyfills.930684be0f926f1d8d85.js:1:9143)
    at m (https://test.sumaris.net/polyfills.930684be0f926f1d8d85.js:1:22589)
    at HTMLInputElement._ (https://test.sumaris.net/polyfills.930684be0f926f1d8d85.js:1:22819)

**Comment by blavenie** [comment]
iPad are not in our target devices. (not yet)
